Updated cmake install action.
As of 9/26/2023, the old version can no longer install CMake 3.16.x and gives
the following error:

Run jwlawson/actions-setup-cmake@v1.4
  with:
    cmake-version: 3.16.x
    github-api-token: ***
Error: Unable to find version matching 3.16.x